In [42]:

import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 40)

file_path = 'input.txt'
df = pd.read_csv(file_path, header=None, sep=' ')
df.columns = ['opponent', 'me']

df

     opponent me
0           B  Z
1           C  Z
2           C  Z
3           A  Y
4           B  Z
...       ... ..
2495        A  X
2496        C  Z
2497        A  X
2498        B  Z
2499        C  X

[2500 rows x 2 columns]

In [43]:
letters_to_shapes = {
    'A': 'rock',
    'B': 'paper',
    'C': 'scissors',
    'X': 'rock',
    'Y': 'paper',
    'Z': 'scissors',
}
shape_values = {
    'rock': 1,
    'paper': 2,
    'scissors': 3,
}
# Replace letters by shape name
df['opponent_shape'] = df['opponent']
df['me_shape'] = df['me']
df.replace({'opponent_shape': letters_to_shapes, 'me_shape': letters_to_shapes}, inplace=True)
# Replace shapes by points
df['opponent_shape_gain'] = df['opponent_shape']
df['me_shape_gain'] = df['me_shape']
df.replace({'opponent_shape_gain': shape_values, 'me_shape_gain': shape_values}, inplace=True)

df['me_battle_gain'] = np.where(df['opponent_shape'] == df['me_shape'], 3, None)
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_shape'] == 'paper'),    6, df['me_battle_gain'])
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_shape'] == 'scissors'), 0, df['me_battle_gain'])
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_shape'] == 'rock'),     0, df['me_battle_gain'])
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_shape'] == 'scissors'), 6, df['me_battle_gain'])
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_shape'] == 'rock'),     6, df['me_battle_gain'])
df['me_battle_gain'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_shape'] == 'paper'),    0, df['me_battle_gain'])

df['me_total_gain'] = df['me_shape_gain'] + df['me_battle_gain']

df

,opponent,me,opponent_shape,me_shape,opponent_shape_gain,me_shape_gain,me_battle_gain,me_total_gain
0,B,Z,paper,scissors,2,3,6,9
1,C,Z,scissors,scissors,3,3,3,6
2,C,Z,scissors,scissors,3,3,3,6
3,A,Y,rock,paper,1,2,6,8
4,B,Z,paper,scissors,2,3,6,9
...,...,...,...,...,...,...,...,...
2495,A,X,rock,rock,1,1,3,4
2496,C,Z,scissors,scissors,3,3,3,6
2497,A,X,rock,rock,1,1,3,4
2498,B,Z,paper,scissors,2,3,6,9
2499,C,X,scissors,rock,3,1,6,7

In [44]:
df['me_total_gain'].sum()

14163

In [45]:
letters_to_objective = {
    'X': 'lose',
    'Y': 'draw',
    'Z': 'win',
}

df['me_objective'] = df['me']
df.replace({'me_objective': letters_to_objective}, inplace=True)

df['me_shape2'] = np.where(df['me_objective'] == 'draw', df['opponent_shape'], None)
df['me_shape2'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_objective'] == 'lose'), 'scissors', df['me_shape2'])
df['me_shape2'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_objective'] == 'win'),  'paper'   , df['me_shape2'])
df['me_shape2'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_objective'] == 'lose'), 'rock'    , df['me_shape2'])
df['me_shape2'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_objective'] == 'win'),  'scissors', df['me_shape2'])
df['me_shape2'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_objective'] == 'lose'), 'paper'   , df['me_shape2'])
df['me_shape2'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_objective'] == 'win'),  'rock'    , df['me_shape2'])

df['me_shape_gain2'] = df['me_shape2']
df.replace({'me_shape_gain2': shape_values}, inplace=True)

df['me_battle_gain2'] = np.where(df['opponent_shape'] == df['me_shape2'], 3, None)
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_shape2'] == 'paper'),    6, df['me_battle_gain2'])
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'rock')     & (df['me_shape2'] == 'scissors'), 0, df['me_battle_gain2'])
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_shape2'] == 'rock'),     0, df['me_battle_gain2'])
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'paper')    & (df['me_shape2'] == 'scissors'), 6, df['me_battle_gain2'])
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_shape2'] == 'rock'),     6, df['me_battle_gain2'])
df['me_battle_gain2'] = np.where((df['opponent_shape'] == 'scissors') & (df['me_shape2'] == 'paper'),    0, df['me_battle_gain2'])

df['me_total_gain2'] = df['me_shape_gain2'] + df['me_battle_gain2']

pd.set_option('display.max_rows', 40)
df

,opponent,me,opponent_shape,me_shape,opponent_shape_gain,me_shape_gain,me_battle_gain,me_total_gain,me_objective,me_shape2,me_shape_gain2,me_battle_gain2,me_total_gain2
0,B,Z,paper,scissors,2,3,6,9,win,scissors,3,6,9
1,C,Z,scissors,scissors,3,3,3,6,win,rock,1,6,7
2,C,Z,scissors,scissors,3,3,3,6,win,rock,1,6,7
3,A,Y,rock,paper,1,2,6,8,draw,rock,1,3,4
4,B,Z,paper,scissors,2,3,6,9,win,scissors,3,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,A,X,rock,rock,1,1,3,4,lose,scissors,3,0,3
2496,C,Z,scissors,scissors,3,3,3,6,win,rock,1,6,7
2497,A,X,rock,rock,1,1,3,4,lose,scissors,3,0,3
2498,B,Z,paper,scissors,2,3,6,9,win,scissors,3,6,9
2499,C,X,scissors,rock,3,1,6,7,lose,paper,2,0,2

In [46]:
df['me_total_gain2'].sum()

12091